const {
	MY_URL,
	PORT,
	GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET,
	ACCESS_SECRET,
	MONGO_URI,
	WEB_URL,
	LIVEKIT_API_KEY,
	LIVEKIT_API_SECRET,
} = process.env;

export const ENV_CONSTANTS = {
	MY_URL: MY_URL!,
	WEB_URL: WEB_URL!,
	PORT: PORT!,
	ACCESS_SECRET: ACCESS_SECRET!,
	//

	GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID!,
	GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET!,
	//

	MONGO_URI: MONGO_URI!,
	LIVEKIT_API_KEY: LIVEKIT_API_KEY!,
	LIVEKIT_API_SECRET: LIVEKIT_API_SECRET!,
};
