import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { UserProvider } from "@/entities/user/UserProvider";
import { SocketConnector } from "@/context/SocketConnector";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { GlobalProvider } from "@/context/GlobalProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ToastContainer />
				<SocketConnector>
					<UserProvider>
						<GlobalProvider>
							<div className="flex">
								<Sidebar />
								{children}
							</div>
						</GlobalProvider>
					</UserProvider>
				</SocketConnector>
			</body>
		</html>
	);
}
